### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "first_name": "Noah",
  "last_name": "Knotta",
  "email": "noah@test.com",
  "password": "password",
  "creator": true
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "mason@test.com",
  "password": "password"
}