@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NTYxNzkxNDl9.Bt1IBKmd_-owv08zU4V3O04t43ArazWOX5vxt9w4164

### Creates a service
POST http://localhost:3000/sites/1/services
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "name": "Test",
  "price": 10,
  "frequency": "Test"
}

### Updates a service
PATCH http://localhost:3000/sites/1/services/7
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "name": "Gardening",
  "price": 50,
  "frequency": "Monthly"
}

### Deletes a service
DELETE http://localhost:3000/sites/1/services/7
Authorization: Bearer {{jwt}}
