@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NTYxNzkxNDl9.Bt1IBKmd_-owv08zU4V3O04t43ArazWOX5vxt9w4164

### View users sites
GET http://localhost:3000/sites.json
Authorization: Bearer {{jwt}}

### View a site
GET http://localhost:3000/sites/5.json

### Creates a site
POST http://localhost:3000/sites.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "name": "Mason's Second Site"
}

### Updates a site
PATCH http://localhost:3000/sites/4.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "name": "Mason's Site 2"
}

### Deletes a site
DELETE http://localhost:3000/sites/6
Authorization: Bearer {{jwt}}